# Generated by Django 3.1.3 on 2020-12-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givmed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='propic.jpg', null=True, upload_to=''),
        ),
    ]
